"""Add sign_requests table for electronic signatures

Revision ID: add_sign_requests
Revises: e9166e499188
Create Date: 2024-09-29 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_sign_requests'
down_revision = 'e9166e499188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SELLER', 'BUYER', 'LESSOR', 'LESSEE', 'BROKER', 'AGENT', 'GUARANTOR', name='signrole'), nullable=False),
    sa.Column('signer_name', sa.String(length=100), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=False),
    sa.Column('signer_phone', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VIEWED', 'SIGNED', 'EXPIRED', 'CANCELED', name='signstatus'), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signature_image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('ix_sign_requests_token', 'token', unique=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_requests')
    # ### end Alembic commands ###
