"""Add sale contract fields to Contract model

Revision ID: add_sale_contract_fields
Revises: e9166e499188
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_sale_contract_fields'
down_revision = 'e9166e499188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add contract_type column
    op.add_column('contract', sa.Column('contract_type', sa.String(length=20), nullable=False, server_default='rental'))
    
    # Add sale contract fields
    op.add_column('contract', sa.Column('buyer_name', sa.String(length=100), nullable=True))
    op.add_column('contract', sa.Column('buyer_phone', sa.String(length=20), nullable=True))
    op.add_column('contract', sa.Column('seller_name', sa.String(length=100), nullable=True))
    op.add_column('contract', sa.Column('seller_phone', sa.String(length=20), nullable=True))
    op.add_column('contract', sa.Column('sale_price', sa.Integer(), nullable=True))
    op.add_column('contract', sa.Column('contract_deposit', sa.Integer(), nullable=True))
    op.add_column('contract', sa.Column('intermediate_payment', sa.Integer(), nullable=True))
    op.add_column('contract', sa.Column('final_payment', sa.Integer(), nullable=True))
    op.add_column('contract', sa.Column('contract_date', sa.Date(), nullable=True))
    op.add_column('contract', sa.Column('final_payment_date', sa.Date(), nullable=True))
    op.add_column('contract', sa.Column('delivery_date', sa.Date(), nullable=True))
    
    # Make existing rental contract fields nullable
    op.alter_column('contract', 'customer_name', nullable=True)
    op.alter_column('contract', 'customer_phone', nullable=True)
    op.alter_column('contract', 'price', nullable=True)
    op.alter_column('contract', 'start_date', nullable=True)
    op.alter_column('contract', 'end_date', nullable=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove sale contract fields
    op.drop_column('contract', 'delivery_date')
    op.drop_column('contract', 'final_payment_date')
    op.drop_column('contract', 'contract_date')
    op.drop_column('contract', 'final_payment')
    op.drop_column('contract', 'intermediate_payment')
    op.drop_column('contract', 'contract_deposit')
    op.drop_column('contract', 'sale_price')
    op.drop_column('contract', 'seller_phone')
    op.drop_column('contract', 'seller_name')
    op.drop_column('contract', 'buyer_phone')
    op.drop_column('contract', 'buyer_name')
    
    # Remove contract_type column
    op.drop_column('contract', 'contract_type')
    
    # Make existing rental contract fields non-nullable again
    op.alter_column('contract', 'end_date', nullable=False)
    op.alter_column('contract', 'start_date', nullable=False)
    op.alter_column('contract', 'price', nullable=False)
    op.alter_column('contract', 'customer_phone', nullable=False)
    op.alter_column('contract', 'customer_name', nullable=False)
    
    # ### end Alembic commands ###

